include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.config.dart'
    - '**/gen/**'
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true
    prefer_final_fields: true
    sort_pub_dependencies: true
    flutter_style_todos: true
    always_use_package_imports: true
    public_member_api_docs: false
